[package]
name = "pdf_to_text"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"

# -- serializer --------------------------------------------------------------
serde = { version = "1.0", features = ["derive", "rc"] }
postcard = { version = "1.1.3", features = ["alloc"] }
serde_json = "1"

# -- converters --------------------------------------------------------------
roxmltree = "0.21"
simplelexer = { version = "0.1.0", git = "https://github.com/witold-k/simplelexer", rev = "9b04c15e393feac77c621dd72b35bc74607054a9" }

# -- fsscan ------------------------------------------------------------------
fsscanner = { version = "0.4.0", git = "https://github.com/witold-k/fsscanner", rev = "a5920ddf9354b18fa0bf82b8474f0872cbe19c85" }

# -- database ----------------------------------------------------------------
token_db = { version = "0.1.0", git = "https://github.com/witold-k/token_db", rev = "c607049f343410e7d0f7e4792af93274fbc90c0e" }

# -- rest --------------------------------------------------------------------
ureq = { version = "3.4", default-features = false, features = ["multipart"] }

